/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgeDistribution: typeof import('./src/components/leftPanel/ageDistribution.vue')['default']
    ApiExample: typeof import('./src/components/examples/ApiExample.vue')['default']
    CEcharts: typeof import('./src/components/common/CEcharts.vue')['default']
    CFooter: typeof import('./src/components/CFooter.vue')['default']
    CHeader: typeof import('./src/components/CHeader.vue')['default']
    CLoading: typeof import('./src/components/common/CLoading.vue')['default']
    CMap: typeof import('./src/components/CMap.vue')['default']
    copy: typeof import('./src/components/MiddleCont copy.vue')['default']
    CPanel: typeof import('./src/components/common/CPanel.vue')['default']
    IndustryRevenue: typeof import('./src/components/rightPanel/industryRevenue.vue')['default']
    LeftPanel: typeof import('./src/components/leftPanel.vue')['default']
    MiddleCardLeftBottom: typeof import('./src/components/MiddleCardLeftBottom.vue')['default']
    MiddleCardLeftTop: typeof import('./src/components/MiddleCardLeftTop.vue')['default']
    MiddleCardRightBottom: typeof import('./src/components/MiddleCardRightBottom.vue')['default']
    MiddleCardRightTop: typeof import('./src/components/MiddleCardRightTop.vue')['default']
    MiddleCont: typeof import('./src/components/MiddleCont.vue')['default']
    MiddleContTitle: typeof import('./src/components/MiddleContTitle.vue')['default']
    ProxyTest: typeof import('./src/components/examples/ProxyTest.vue')['default']
    RankingOfScenicSpots: typeof import('./src/components/leftPanel/rankingOfScenicSpots.vue')['default']
    RealTimeHotWords: typeof import('./src/components/rightPanel/realTimeHotWords.vue')['default']
    ReceptionOfTourists: typeof import('./src/components/leftPanel/receptionOfTourists.vue')['default']
    ReviewList: typeof import('./src/components/common/ReviewList.vue')['default']
    RightPanel: typeof import('./src/components/rightPanel.vue')['default']
    SaleList: typeof import('./src/components/common/SaleList.vue')['default']
    SaleListExample: typeof import('./src/components/examples/SaleListExample.vue')['default']
    TitleDemo: typeof import('./src/components/examples/TitleDemo.vue')['default']
    Top5Tourists: typeof import('./src/components/rightPanel/top5Tourists.vue')['default']
    VanCircle: typeof import('vant/es')['Circle']
  }
}
